# Generated by roxytest: do not edit by hand!

# File R/time.r: @tests

test_that("Function get_dpy() @ L47", {
  # Default value when no parent frame context
  expect_equal(
    get_dpy(),
    365
  )
  
  # Test with parent frame containing cycle_length variables
  expect_equal(
    local({
      cycle_length_days <- 365.25
      cycle_length_years <- 1
      get_dpy()
    }),
    365.25
  )
  
  # Test with different days per year (e.g., 360-day year)
  expect_equal(
    local({
      cycle_length_days <- 30
      cycle_length_years <- 1/12
      get_dpy()
    }),
    360
  )
  
  # Test with vector inputs (uses first element)
  expect_equal(
    local({
      cycle_length_days <- c(365, 730)
      cycle_length_years <- c(1, 2)
      get_dpy()
    }),
    365
  )
})


test_that("Function time_in_days() @ L137", {
  # Days
  expect_equal(
    time_in_days("days", 365),
    1
  )
  
  # Weeks
  expect_equal(
    time_in_days("weeks", 365),
    7
  )
  
  # Months (365-day year)
  expect_equal(
    time_in_days("months", 365),
    365/12
  )
  
  # Years
  expect_equal(
    time_in_days("years", 365),
    365
  )
  
  # Case insensitivity
  expect_equal(
    time_in_days("DAYS", 365),
    1
  )
  expect_equal(
    time_in_days("Days", 365),
    1
  )
  expect_equal(
    time_in_days("WEEKS", 365),
    7
  )
  expect_equal(
    time_in_days("Months", 365),
    365/12
  )
  expect_equal(
    time_in_days("YEARS", 365),
    365
  )
  
  # Different days_per_year values
  expect_equal(
    time_in_days("months", 360),
    30
  )
  expect_equal(
    time_in_days("years", 365.25),
    365.25
  )
  
  # Invalid unit returns NULL
  expect_null(
    time_in_days("invalid", 365)
  )
})

