# Generated by roxytest: do not edit by hand!

# File R/formatting.r: @tests

test_that("Function quoted_list_string() @ L21", {
  expect_equal(
   quoted_list_string(c('a','b','c')),
   '"a", "b", "c"'
  )
})


test_that("Function get_indefinite_article() @ L51", {
  expect_equal(
   get_indefinite_article('fruit'),
   'a'
  )
  
  expect_equal(
   get_indefinite_article('apple'),
   'an'
  )
})


test_that("Function create_param_formatter() @ L80", {
  expect_equal(
   create_param_formatter(digits = 4)(0.1234567),
   "0.1235"
  )
})


test_that("Function to_list_item_output() @ L122", {
  expect_equal(
   to_list_item_output(mtcars[1:2,1:3]),
   "\n                      mpg cyl disp\n        Mazda RX4      21   6  160\n        Mazda RX4 Wag  21   6  160"
  )
  expect_equal(
   to_list_item_output(mtcars[1:2,1:3], n = 2),
   "\n                  mpg cyl disp\n    Mazda RX4      21   6  160\n    Mazda RX4 Wag  21   6  160"
  )
  expect_equal(
   to_list_item_output(mtcars[1:2,1:3], skip = 1, n = 2),
   "\n    Mazda RX4      21   6  160\n    Mazda RX4 Wag  21   6  160"
  )
})

