# Generated by roxytest: do not edit by hand!

# File R/factors.r: @tests

test_that("Function clean_factors() @ L16", {
  expect_equal(
   clean_factors(data.frame(a = 'foo', b = 1, stringsAsFactors = TRUE)),
   data.frame(a = 'foo', b = 1, stringsAsFactors = FALSE)
  )
})

