# Generated by roxytest: do not edit by hand!

# File R/formula_input.r: @tests

test_that("Function formulaInput() @ L71", {
  result <- formulaInput("test_id", value = "x + y")
  expect_true(inherits(result, "shiny.tag.list"))
})


test_that("Function updateFormulaInput() @ L127", {
  # updateFormulaInput requires a session object, so we test it exists
  expect_true(is.function(updateFormulaInput))
})

