# Generated by roxytest: do not edit by hand!

# File R/math.r: @tests

c("test_that(\"Function prob_to_odds() @ L17\", {\n  expect_equal(prob_to_odds(0.25), 1/3)\n  expect_equal(prob_to_odds(0.75), 3)\n  expect_equal(prob_to_odds(1), Inf)\n  expect_equal(prob_to_odds(0), 0)\n})\n", "test_that(\"Function prob_to_odds() @ L17\", {\n  expect_equal(odds_to_prob(1/3), 0.25)\n  expect_equal(odds_to_prob(3), 0.75)\n  expect_equal(odds_to_prob(Inf), 1)\n  expect_equal(odds_to_prob(0), 0)\n})\n")
